### ISSUE TITLE
Since update, formie notification jobs are failing : Calling unknown method: craft\console\Request::getQueryStringWithoutPath()

### ISSUE THREAD

**Issue by francoislevesque** [pierrestoffe/craft-language-redirector#25]
We are using Formie to send email notification in a queue.

While sending the notification (in the queu), craft-language-redirector throws an error.

Here's the error log :

`2024-12-13 18:03:56 [queue.ERROR] [yii\base\UnknownMethodException] Calling unknown method: craft\console\Request::getQueryStringWithoutPath() {"trace":["#0 /Users/francoislevesque/code/witify/vendor/pierrestoffe/craft-language-redirector/src/services/LanguageRedirectorService.php(490): yii\\base\\Component->__call('getQueryStringW...', Array)","#1 /Users/francoislevesque/code/witify/vendor/pierrestoffe/craft-language-redirector/src/services/LanguageRedirectorService.php(42): pierrestoffe\\languageredirector\\services\\LanguageRedirectorService->_setQueryParameters()","#2 /Users/francoislevesque/code/witify/vendor/pierrestoffe/craft-language-redirector/src/LanguageRedirector.php(56): pierrestoffe\\languageredirector\\services\\LanguageRedirectorService->__construct()","#3 [internal function]: pierrestoffe\\languageredirector\\LanguageRedirector->pierrestoffe\\languageredirector\\{closure}(Object(yii\\base\\Event))","#4 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\\base\\Event))","#5 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Component.php(650): yii\\base\\Event::trigger('craft\\\\web\\\\twig\\\\...', 'init', Object(yii\\base\\Event))","#6 /Users/francoislevesque/code/witify/vendor/craftcms/cms/src/web/twig/variables/CraftVariable.php(94): yii\\base\\Component->trigger('init')","#7 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\\web\\twig\\variables\\CraftVariable->init()","#8 /Users/francoislevesque/code/witify/vendor/craftcms/cms/src/web/twig/variables/CraftVariable.php(81): yii\\base\\BaseObject->__construct(Array)","#9 /Users/francoislevesque/code/witify/vendor/verbb/formie/src/helpers/Variables.php(213): craft\\web\\twig\\variables\\CraftVariable->__construct()","#10 /Users/francoislevesque/code/witify/vendor/verbb/formie/src/services/Emails.php(84): verbb\\formie\\helpers\\Variables::getParsedValue('{field.name1.fi...', Object(verbb\\formie\\elements\\Submission), Object(verbb\\formie\\elements\\Form), Object(verbb\\formie\\models\\Notification))","#11 /Users/francoislevesque/code/witify/vendor/verbb/formie/src/services/Emails.php(323): verbb\\formie\\services\\Emails->renderEmail(Object(verbb\\formie\\models\\Notification), Object(verbb\\formie\\elements\\Submission))","#12 /Users/francoislevesque/code/witify/vendor/verbb/formie/src/services/Submissions.php(229): verbb\\formie\\services\\Emails->sendEmail(Object(verbb\\formie\\models\\Notification), Object(verbb\\formie\\elements\\Submission), Object(verbb\\formie\\jobs\\SendNotification))","#13 /Users/francoislevesque/code/witify/vendor/verbb/formie/src/jobs/SendNotification.php(66): verbb\\formie\\services\\Submissions->sendNotificationEmail(Object(verbb\\formie\\models\\Notification), Object(verbb\\formie\\elements\\Submission), Object(verbb\\formie\\jobs\\SendNotification))","#14 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2-queue/src/Queue.php(243): verbb\\formie\\jobs\\SendNotification->execute(Object(craft\\queue\\Queue))","#15 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage('103578', 'O:34:\"verbb\\\\for...', '300', '1')","#16 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute('103578', 'O:34:\"verbb\\\\for...', '300', '1', '41289')","#17 [internal function]: yii\\queue\\cli\\Command->actionExec('103578', '300', '1', '41289')","#18 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#19 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#20 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction('exec', Array)","#21 /Users/francoislevesque/code/witify/vendor/craftcms/cms/src/console/ControllerTrait.php(88): yii\\console\\Controller->runAction('exec', Array)","#22 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Module.php(552): craft\\queue\\Command->runAction('exec', Array)","#23 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction('queue/exec', Array)","#24 /Users/francoislevesque/code/witify/vendor/craftcms/cms/src/console/Application.php(91): yii\\console\\Application->runAction('queue/exec', Array)","#25 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction('queue/exec', Array)","#26 /Users/francoislevesque/code/witify/vendor/craftcms/cms/src/console/Application.php(122): yii\\console\\Application->handleRequest(Object(craft\\console\\Request))","#27 /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest(Object(craft\\console\\Request))","#28 /Users/francoislevesque/code/witify/craft(13): yii\\base\\Application->run()","#29 {main}"],"memory":44818544,"exception":"[object] (yii\\base\\UnknownMethodException(code: 0): Calling unknown method: craft\\console\\Request::getQueryStringWithoutPath() at /Users/francoislevesque/code/witify/vendor/yiisoft/yii2/base/Component.php:308)"} 
`

**Comment by pierrestoffe** [comment]
Thanks for the [PR](https://github.com/pierrestoffe/craft-language-redirector/pull/27) @francoislevesque.
Could you confirm that using release [3.1.3](https://github.com/pierrestoffe/craft-language-redirector/releases/tag/3.1.3) fixes your issue please?

**Comment by boboldehampsink** [comment]
This is also the case for 2.x

**Comment by francoislevesque** [comment]
3.1.3 works for me @pierrestoffe , thank you !

**Comment by pierrestoffe** [comment]
The same fix was just published for 1.x and 2.x as well.
